### ISSUE TITLE
break readme

### ISSUE THREAD

**Issue by metya** [TezRomacH/python-package-template#164]
У тебя ридми сломался)
![изображение](https://user-images.githubusercontent.com/968934/96295325-5fe2c280-0ff6-11eb-957f-eea3afba8d5a.png)

**Comment by TezRomacH** [comment]
Приветик, Тимур!

Ничего не сломалось 😄 Это же просто текст, который потом будет заполнен генератором `cookicutter`, хех)) 

Т.е ты запускаешь темплейт, вводишь значения как описано туть https://github.com/TezRomacH/python-package-template#input-variables и генератор подставляет все в твой ридми)


Попробуй запустить
```
pip install -U cookiecutter lice &&  cookiecutter gh:TezRomacH/python-package-template
```

и все __пофиксится__ хех

**Comment by metya** [comment]
АААА. понял)
