### ISSUE TITLE
Build action fails as darglint checks the .venv folder made in previous step

### ISSUE THREAD

**Issue by Wiserfunding-CTO** [TezRomacH/python-package-template#311]
## 🐛 Bug Report

The GitHub Action build is calling Make which runs darglint against the root folder including .venv

## 🔬 How To Reproduce

1. Create a new project with this template using python 3.9 and push to remote origin

Or to reproduce locally

 $ python3 -m venv .venv
 $ make check-codestyle

### Code sample

n/a

### Environment

Python 3.9.4

### Screenshots

![image](https://user-images.githubusercontent.com/79464350/124481845-a2c11200-dda0-11eb-8d08-91b390fd81c0.png)

![image](https://user-images.githubusercontent.com/79464350/124481929-b53b4b80-dda0-11eb-844b-0de876d23961.png)

## 📈 Expected behavior

Needs to exclude .venv or maybe darglint first then create .venv

**Comment by TezRomacH** [comment]
Thanks for reporting. I have reproduced this bug, now I'm gonna fix it

**Comment by TezRomacH** [comment]
The fix is in the latest release

```bash
cookiecutter gh:TezRomacH/python-package-template --checkout v1.0.3
```

Check it out! If there is still an error, please reopen this issue 👍🏻

**Comment by Wiserfunding-CTO** [comment]
Nice fix. Impressively quick response.

**Comment by Wiserfunding-CTO** [comment]
Spoke too soon. Same problem with bandit in the check-safety step

**Comment by TezRomacH** [comment]
Well, okay :) fix will be the almost the same, `bandit` has `exclude` parameter

**Comment by TezRomacH** [comment]
I'm here again 😄 
Try now, please 🙏🏻
