### ISSUE TITLE
RuntimeError when commit

### ISSUE THREAD

**Issue by dbinary** [TezRomacH/python-package-template#34]
## 🐛 Bug Report

I got the error `RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.7'`, when try to first commit.

## 🔬 How To Reproduce

1. cookiecutter gh:TezRomacH/python-package-template
2. Follow instructions
3. After git add, git commit and get the error.

### Code sample
```bash
git commit -m ":tada: Initial commit"
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/home/dbinary/.cache/pypoetry/virtualenvs/smplnotes-P5WiIkN--py3.8/bin/python', '-mvirtualenv', '/home/dbinary/.cache/pre-commit/repobgj1aqa4/py_env-python3.7', '-p', 'python3.7')
return code: 1
expected return code: 0
stdout:
    RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.7'
    
stderr: (none)
Check the log at /home/dbinary/.cache/pre-commit/pre-commit.log
```

### Environment

* OS: Arch Linux
* Python 3.8.2

## 📈 Expected behavior

Make a commit without errors.

[pre-commit.log](https://github.com/TezRomacH/python-package-template/files/4631077/pre-commit.log)

**Comment by TezRomacH** [comment]
Hi! Thank you for the bug report! 
According to the error text, you don't have `python3.7`, which is the version required version for the template.

I can see in the logs that you're running the program with `python3.8`. Can you please try to do the same, but on` python3.7`? Just to ensure the `3.7` works properly.

As a hotfix, I can suggest you put it in `.pre-commit-config.yaml':
```
default_language_version:
  python: python3.8
```

And I'll make a fix for it tomorrow.  Now it's 1:00 a.m. Moscow time 😄

**Comment by TezRomacH** [comment]
Slowpoke time!

I'have just made a fix for this. In installation there is now a parameter `minimal_python_version` 😍
