### ISSUE TITLE
Migrate pytest configuration to pyproject.toml

### ISSUE THREAD

**Issue by johnthagen** [TezRomacH/python-package-template#361]
## 🚀 Feature Request

Pytest supports configuration via `pyproject.toml`. Migrate its configuration from `setup.cfg` to `pyproject.toml`.

- https://docs.pytest.org/en/6.2.x/customize.html#pyproject-toml

## 🔈 Motivation

`pyproject.toml` is becoming the standard configuration location for Python package. Doing this takes one step closer to removing the need for the `setup.cfg` file and simplify the overall project.

**Comment by johnthagen** [comment]
When `darglint` supports `pyproject.toml` (https://github.com/terrencepreilly/darglint/issues/130) `setup.cfg` could be removed entirely from this template.

**Comment by TezRomacH** [comment]
Thanks, @johnthagen that's gread. I didn't know `pytest` is already accept `pyproject.toml`. I will include this update in the next minor version

**Comment by TezRomacH** [comment]
Done in `v1.1.0` :)
