### ISSUE TITLE
Maybe switch from Makefile to Invoke?

### ISSUE THREAD

**Issue by paw-lu** [TezRomacH/python-package-template#41]
## 🚀 Feature Request

Great work here @TezRomacH . I'm looking forward to seeing this project evolve!

This is honestly less of a feature request, more of a response to your cry for help comment on your Makefile.

> ##! Please tell me how to use `for loops` to create variables in Makefile :(
> ##! If you have better idea, please PR me in https://github.com/TezRomacH/python-package-template

Are you familiar with [Invoke](http://www.pyinvoke.org/)? It's a Python alternative to GNU Make, which might help you with your Makefile troubles (for loops, flags). I just wanted to bring it to your attention to see if it could make your life easier.

## 🔈 Motivation

To save you from using Make.

## 🛰 Alternatives

Make is still useful and a good choice because (almost) every machine has it already installed and is a well-known standard.

Thanks for the cool project!

**Comment by TezRomacH** [comment]
Hi! I've never heard of Invoke before. 
Looks very exciting 🙂 
I'll see if I should change the Makefile for this.

Thanks!

**Comment by paw-lu** [comment]
I'm open to writing the Invoke implementation if you end up interested in it in the future.

Cheers!

**Comment by yasirroni** [comment]
Windows does not support make natively, and the most recommended of make installation is using chocolatey. Unfortunately, chocolatey free license seems not for commercial use.
